name: Build and deploy election-portal to Azure Web App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install and build frontend
        working-directory: ./election-portal/frontend
        run: |
          npm ci
          npm run build

      - name: Install backend dependencies
        working-directory: ./election-portal/backend
        run: |
          npm ci

      - name: Prepare deployment package (copy frontend build into backend and zip)
        run: |
          rm -rf election-portal/backend/build || true
          cp -a election-portal/frontend/build election-portal/backend/build
          cd election-portal/backend
          zip -r ../app-deploy.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: election-portal/app-deploy.zip
